### PR TITLE
Weapon stat corrections and new stats

### PR DESCRIPTION
**Pull request by Jacoby6000**
Trying to upstream some of the changes we've made.  If you're not interested I can omit these and keep it all to my fork.

### CODE REVIEW

**Comment by aardvarkk** [comment]
@Jacoby6000 I appreciate it. I will try to make you a collaborator here so you can write to the repo whenever you want. I'll see how it goes...

**Comment by aardvarkk** [comment]
@Jacoby6000 Invite sent

**Comment by Jacoby6000** [comment]
The current iteration is quite a bit ahead of your repo.  We've added dark mode and a few other features, which you may have some objections to. I know I'd like to make some changes to the dark mode styling but I figured it was good enough as-is and I can tweak it later.  The latest is deployed at [polehammer.net](https://polehammer.net) if you want to check it out.  There's a couple of antipatterns I shoehorned in to the bottom of the index.html which I need to clean up, also.

Latest is actually [here](https://polehammer-a740e--pr24-1vx-zj5xlayb.web.app/) but this is unreleased content :p

**Comment by aardvarkk** [comment]
@Jacoby6000 I'm happy to basically hand off the repo for you to take it wherever you want. I'll maintain access but you should have full write access to take it where you'd like. Once you accept the collaboration invite you'll have full push access and you can just use this repo as your primary rather than having to maintain a fork.

**Comment by Jacoby6000** [comment]
I'll move development to here shortly.  Do you mind that I will be overriding your integrations with some free firebase integrations?  (they came with the domain name [polehammer.net](https://polehammer.net))

**Comment by aardvarkk** [comment]
Nope -- take the repo wherever you need it to go!

**Comment by aardvarkk** [comment]
@Jacoby6000 Just invited you again to be a collaborator on the repo. The last invite expired. You'll have to accept the invite before you can have write access. Looking forward to seeing where you take it. I re-purchased on Steam and was playing a bunch of Tenosian stuff last night. Very fun!

**Pull request closed without merging**
