### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by Jacoby6000**

### CODE REVIEW

**Comment by aardvarkk** [comment]
@Jacoby6000 Do you have permission to merge this yourself? If not, I can give it to you.

**Comment by Jacoby6000** [comment]
I have access! I was waiting for CI to pass before merging and just forgot about it

**Comment by Jacoby6000** [comment]
By the way, check out https://reddit.com/u/polehammerposter

**Comment by aardvarkk** [comment]
@Jacoby6000 Hah, that's epic! Well done!

**Comment by aardvarkk** [comment]
@Jacoby6000 How'd you build that out? Did you somehow train a model on your data and then hook up a chatbot to talk about it?

**Comment by Jacoby6000** [comment]
This is all just gpt4

I send it a "system prompt" which tells it the character to act out, and then I insert a csv containing data of the weapons mentioned in the post. Chat gpt does pretty much everything else.

________________________________

**Comment by aardvarkk** [comment]
Man, that's intense. Cool idea!

**Pull request merged**
